### ISSUE TITLE
Проверка Д/3 Lesson 1

### ISSUE THREAD

**Issue by VadimZhiltsov** [stasguma/stasguma.github.io#3]
1. Выравнять отступы в коде.
2. Разделить CSS файлы на два normalize.css, где будет нормализация css свойтв браузеров и второй, где будут свои стили.
3. Классы надо называть более семантично, исходя из классов fp, sp, tp, four-p не понятно что кроется за их содержимым. Хорошие примеры: aboutMyself, feedback, etc.
4. Картинку всё таки надо сделать тегом img, это позволит легче менять вёрстку и этот момент очень важен для web accessibility, всякие screen reader'ы  не поймут по бекграунду, что там картинка.
5. Номер телефона можно сделать ссылкой с протоколом callto:. Это позволит звонить по номеру веголишь клинув на него.
6. На wrapper'e стоит длина 514px и ещё падингов на 128px, 
   На вложенные блочные элементы так же навешена длина 514px, из-за чего настоящая длина wrapper'a увеличивается по размеру контента, а не указанной длины.
   Cтоит убрать длину с вложеных блочных элементов, т.к. они поумолчанию 100% длины родителя занимают, и увеличить длину wrapper'a

**Comment by stasguma** [comment]
исправил

**Comment by VadimZhiltsov** [comment]
Зачёт
